### ISSUE TITLE
RecursionError for multi-input vitejs config

### ISSUE THREAD

**Issue by quard8** [MrBin99/django-vite#139]
Hi!

I found a strange bug, and I can't find a solution for this. 

I'm using latest django-vite and vitejs packages with multi-input for different apps. 

My vitejs config for multi-input:

```js
{
input: {
    app: "src/index.jsx",
    shopify_app: "src/index.shopify.jsx",
    shopify_subscription: "src/index.shopify.subscription.jsx",
    }
}
```

With a single "app" input, everything is working fine. 

What I'm missing?

Error is:
```
Environment:

Request Method: GET
Request URL: skip

Django Version: 4.2.13
Python Version: 3.10.14

Template error:
In template /Users/quard/dev/storista/storista-server/app/templates/app/index.html, error at line 19
   maximum recursion depth exceeded
   9 :         <meta name="theme-color" content="#000000"/>
   10 :         <meta name="description" content="Storista.io dashboard"/>
   11 :         <link rel="icon" type="image/svg+xml" href="/static/images/logo.svg">
   12 :         <link rel="mask-icon" href="/static/images/logo.svg">
   13 :         <link rel="shortcut icon" type="image/jpg" href="/static/images/logo.png"/>
   14 :         <link rel="preconnect" href="https://fonts.googleapis.com">
   15 :         <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
   16 :         <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">
   17 :         <title>Dashboard &mdash; Storista</title>
   18 : 
   19 :          {% vite_asset 'src/index.jsx' %} 
   20 :         <link href="/static/css/app.css" rel="stylesheet">
   21 :         <link rel="preconnect" href="https://cdn.shopify.com/" />
   22 :         <link
   23 :           rel="stylesheet"
   24 :           href="https://cdn.shopify.com/static/fonts/inter/inter.css"
   25 :         />
   26 : 
   27 :     </head>
   28 :     <body>
   29 :         <noscript>You need to enable JavaScript to run this app.</noscript>


Traceback (most recent call last):
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/quard/dev/storista/storista-server/app/views/__init__.py", line 143, in index
    return render(
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/template/library.py", line 237, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django/utils/safestring.py", line 53, in wrapper
    return safety_marker(func(*args, **kwargs))
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django_vite/templatetags/django_vite.py", line 67, in vite_asset
    return DjangoViteAssetLoader.instance().generate_vite_asset(path, app, **kwargs)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django_vite/core/asset_loader.py", line 779, in generate_vite_asset
    return app_client.generate_vite_asset(path, **kwargs)
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django_vite/core/asset_loader.py", line 316, in generate_vite_asset
    tags.extend(self._load_css_files_of_asset(path))
  File "/Users/quard/dev/storista/storista-server/venv/lib/python3.10/site-packages/django_vite/core/asset_loader.py", line 422, in _load_css_files_of_asset
    return self._generate_css_files_of_asset(

    manifest_entry = self.manifest.get(path)

Exception Type: RecursionError at /
Exception Value: maximum recursion depth exceeded
```

**Comment by Niicck** [comment]
Can you share a copy of your `manifest.json` and the `path` that's causing trouble?

**Comment by pieterbeulque** [comment]
I have a similar problem using multiple entry points, my server goes OOM, might be caused by this recursion too.

**Comment by Niicck** [comment]
There's an interesting problem with your manifest: it contains a circular import that's causing django-vite to break:

```json
    "_style-Dxcc6stL.js": {
      "file": "assets/style-Dxcc6stL.js",
      "name": "style",
      "imports": [
        "_vendor-B9930neC.js"
      ],
      "css": [
        "assets/style-wjhWB3DI.css"
      ]
    },
  ...
  "_vendor-B9930neC.js": {
      "file": "assets/vendor-B9930neC.js",
      "name": "vendor",
      "imports": [
        "_style-Dxcc6stL.js"
      ],
      "css": [
        "assets/vendor-GH1NkoEL.css"
      ]
    },
```

If you can remove that circular dependency from the imports in your code, that should work around this issue. Long term though, django-vite should probably support this since its a valid vite configuration. I've got a draft PR that I'm working on. Need to brush off those leetcode recursion skills.

If you don't mind, can we use your Shopify manifest as an example in our test suite?

**Comment by quard8** [comment]
Wow, I didn't realize this is circular imports in my code. Thanks for pointing on this!

Sure, you can use manifest.
