### ISSUE TITLE
aws elastic beanstalk - django_vite template doesn't load 

### ISSUE THREAD

**Issue by thekubilay** [MrBin99/django-vite#39]
normally it's works fine in production on VPS server. but we are moving the server from VPS to AWS elastic beanstalk. and when I deployed the django app. Django part is working fine but it's look like django_vite giving some error and vue is not loading. (I am using the same settings which is what I used it on VPS server and it went fine.)

I checked the error logs and there is this error. 
```

module = import_module(entry[1])
Apr  5 14:45:54 ip-172-31-37-154 web: File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
Apr  5 14:45:54 ip-172-31-37-154 web: return _bootstrap._gcd_import(name[level:], package, level)
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap>", line 991, in _find_and_load
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Apr  5 14:45:54 ip-172-31-37-154 web: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Apr  5 14:45:54 ip-172-31-37-154 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django_vite/templatetags/django_vite.py", line 45, in <module>
Apr  5 14:45:54 ip-172-31-37-154 web: path_join(
Apr  5 14:45:54 ip-172-31-37-154 web: File "/usr/lib64/python3.8/posixpath.py", line 76, in join
Apr  5 14:45:54 ip-172-31-37-154 web: a = os.fspath(a)
Apr  5 14:45:54 ip-172-31-37-154 web: TypeError: expected str, bytes or os.PathLike object, not NoneType
Apr  5 14:45:54 ip-172-31-37-154 web: During handling of the above exception, another exception occurred:
Apr  5 14:45:54 ip-172-31-37-154 web: Traceback (most recent call last):
Apr  5 14:45:54 ip-172-31-37-154 web: File "/var/app/venv/staging-LQM1lest/lib/python3.8/site-packages/django/template/utils.py", line 66, in __getitem__
Apr  5 14:45:54 ip-172-31-37-154 web: return self._engines[alias]
Apr  5 14:45:54 ip-172-31-37-154 web: KeyError: 'django'
```

any idea what's happening here?

**Comment by MrBin99** [comment]
Hi,

I think your error is written here :
```
Apr  5 14:45:54 ip-172-31-37-154 web: TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by thekubilay** [comment]
hello, thank you for response. I know the line that you pointed out. But it doesn't give any lead. for example, where is expected str, why getting None;

here, what I am using in settings.py 

```
if DEBUG:
  DJANGO_VITE_ASSETS_PATH = BASE_DIR / "app/src"
  STATIC_URL = '/static/'
  STATICFILES_DIRS = [
    BASE_DIR / "static",
    DJANGO_VITE_ASSETS_PATH,
  ]
  MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
  MEDIA_URL = '/media/'

else:
  # Where ViteJS assets are built.   # aws settings
  AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
  AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
  AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
  AWS_DEFAULT_ACL = 'public-read'
  AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
  AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}

  # s3 static settings
  AWS_S3_FILE_OVERWRITE = False
  AWS_LOCATION = 'static'
  STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'
  STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

  # s3 public media settings
  PUBLIC_MEDIA_LOCATION = 'media'
  MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
  DEFAULT_FILE_STORAGE = "reactool.aws_storages.MediaStorage"

  STATIC_ROOT = BASE_DIR / 'static'
  DJANGO_VITE_ASSETS_PATH = BASE_DIR / "static"
  STATICFILES_DIRS = [
       DJANGO_VITE_ASSETS_PATH
  ]
```

is this line `TypeError: expected str, bytes or os.PathLike object, not NoneType` points where in aws settings? Because if on DEBUG mode. there is no issue.

**Comment by MrBin99** [comment]
Which version of `django-vite` are you using ?

**Comment by thekubilay** [comment]
it's `django-vite==1.2.1`

**Comment by MrBin99** [comment]
Try updating to `2.X`.
Before `2.X` path specified with `Pathlib` were not fully supported.

**Comment by thekubilay** [comment]
okay, I updated. now i can see where the problem is. error logs spits `AttributeError: 'Settings' object has no attribute 'DJANGO_VITE_ASSETS_PATH'` but, i am giving the it correctly. 

```
 STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
 DJANGO_VITE_STATIC_URL = STATIC_URL
 DJANGO_VITE_ASSETS_PATH = str(STATIC_URL)
 STATIC_ROOT = BASE_DIR / "static"
```

by the way there is no error on dev mode. I finds the `DJANGO_VITE_ASSETS_PATH` but when it goes to production. aws eb spits  `'Settings' object has no attribute 'DJANGO_VITE_ASSETS_PATH'`

**Comment by thekubilay** [comment]
thank you for pointing out the new version. finally got the error context. 
so I need change two things. gave the   `STATIC_ROOT = "static"` without `BASE_DIR` and updated the django.config file in the .ebextensions

option_settings:
  aws:elasticbeanstalk:environment:proxy:staticfiles:
    /static: static

this solves the problem on AWS elastic beanstalk production.
